---
- name: Install zabbix
  hosts: all
  become: true

  tasks:
  - name: Install repos
    yum:
      name: "http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm"
      state: present

  - name: install zabbix-agent
    yum:
      name: zabbix-agent
      state: present

  - name: Start zabbix-agent
    service:
      name: zabbix-agent
      state: restarted
